import NotRecognizedCommand from "@/components/NotRecognizedCommand";
import Prompt from "@/components/Prompt";
import styles from "@/styles/Home.module.css";
import commands from "@/utils/comands/comands";
import Head from "next/head";
import { Fragment, KeyboardEvent, useState } from "react";

export default function Home() {
	const [render, setRender] = useState([Prompt]);
	const [command, setCommand] = useState("");

	const onKeyDown = (event: KeyboardEvent<HTMLInputElement>) => {
		const value: any = event.currentTarget.value.replace(" ", "_");
		setCommand(value);

		const commandRender = commands(value);
		setRender(prevState => [...prevState, ...commandRender]);
	};	

	return (
		<>
			<Head>
				<title>Gabriel Silvério</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				{render.map((Component, index) => (
					<Fragment key={index}>
						<Component onKeyDown={onKeyDown}/>
					</Fragment>
				))}
			</main>
		</>
	);
}
